[package]
name = "opod"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
igd = "0.12.0"
notify = "4.0.17"
regex = "1.0.0"
log = "0.4.0"
env_logger = "0.8.4"
